### ISSUE TITLE
php 8.2 | SeoPro

### ISSUE THREAD

**Issue by sh1sh1n** [19th19th/OCStore-LiveOpencart#9]
После включения настроек SeoPro получаем:
Creation of dynamic property SeoPro::$cache is deprecated in …/system/library/seopro.php on line 41

После
`private $db;`
 надо добавить:
`private $cache;`

… получаем ошибки при включении кеша SePro:
Automatic conversion of false to array is deprecated in …/system/library/seopro.php on line 416
Automatic conversion of false to array is deprecated in …/system/library/seopro.php on line 417
Automatic conversion of false to array is deprecated in …/system/library/seopro.php on line 617 

Идём в 414 строку и меняем её на:
`				if($query->num_rows && is_array($query->rows)) {`

В итоге работает без ошибок на php 8.2

**Comment by 19th19th** [comment]
Cпасибо!

**Comment by sh1sh1n** [comment]
Не сработало: если кеш очистить, то снова предупреждения высыпаются. 

В итоге, сделал так: 

 с 622 строки:
```
	if ($this->config->get('config_seo_url_cache')) {
		if (!is_array($this->product_categories)) {
			$this->product_categories = [];
		}
		$this->product_categories[$product_id] = $category_id;
	}
		return $category_id;
	}
```

С 399 строки:
```
if ($this->config->get('config_seo_url_cache')) {
			$this->keywords = $this->cache->get('seopro.keywords');
			$this->queries = $this->cache->get('seopro.queries');

		if (!$this->keywords || !is_array($this->keywords)) {
			$this->keywords = [];
		}
		if (!$this->queries || !is_array($this->queries)) {
			$this->queries = [];
		}

		if (empty($this->keywords) || empty($this->queries)) {
					$sql_keyword = 'keyword';
					
					if ($this->config->get('config_seopro_lowercase')) {
						$sql_keyword = 'LCASE(keyword) as ' . $sql_keyword;
					}
					$sql = "SELECT " . $sql_keyword . ", query, store_id, language_id FROM " . DB_PREFIX . "seo_url WHERE 1";
					$query = $this->db->query($sql);
				
        if ($query->num_rows && is_array($query->rows)) {
            foreach ($query->rows as $row) {
						$this->keywords[$row['query']][$row['store_id']][$row['language_id']] = $row['keyword'];
						$this->queries[$row['keyword']][$row['store_id']][$row['language_id']] = $row['query'];
					}
				}
			}
		}
```

Пока, вроде, работает.

**Comment by 19th19th** [comment]
> Не сработало: если кеш очистить, то снова предупреждения высыпаются.
> 
> В итоге, сделал так:
> 
> с 622 строки:
> 
> ```
> 	if ($this->config->get('config_seo_url_cache')) {
> 		if (!is_array($this->product_categories)) {
> 			$this->product_categories = [];
> 		}
> 		$this->product_categories[$product_id] = $category_id;
> 	}
> 		return $category_id;
> 	}
> ```
> 
> С 399 строки:
> 
> ```
> if ($this->config->get('config_seo_url_cache')) {
> 			$this->keywords = $this->cache->get('seopro.keywords');
> 			$this->queries = $this->cache->get('seopro.queries');
> 
> 		if (!$this->keywords || !is_array($this->keywords)) {
> 			$this->keywords = [];
> 		}
> 		if (!$this->queries || !is_array($this->queries)) {
> 			$this->queries = [];
> 		}
> 
> 		if (empty($this->keywords) || empty($this->queries)) {
> 					$sql_keyword = 'keyword';
> 					
> 					if ($this->config->get('config_seopro_lowercase')) {
> 						$sql_keyword = 'LCASE(keyword) as ' . $sql_keyword;
> 					}
> 					$sql = "SELECT " . $sql_keyword . ", query, store_id, language_id FROM " . DB_PREFIX . "seo_url WHERE 1";
> 					$query = $this->db->query($sql);
> 				
>         if ($query->num_rows && is_array($query->rows)) {
>             foreach ($query->rows as $row) {
> 						$this->keywords[$row['query']][$row['store_id']][$row['language_id']] = $row['keyword'];
> 						$this->queries[$row['keyword']][$row['store_id']][$row['language_id']] = $row['query'];
> 					}
> 				}
> 			}
> 		}
> ```
> 
> Пока, вроде, работает.

Пришлите на help@liveopencart.ru пожалуйста, пока не можем разобраться
